### PR TITLE
add Katy Moe to students

### PR DESCRIPTION
**Pull request by kmoe**

### CODE REVIEW

**Comment by ericdouglas** [comment]
Great, @kmoe ! Thanks for make your registration! :tada: :smile:

**Comment by ericdouglas** [comment]
@kmoe just two things:

1. the name of your file should be equal as your GitHub username. In your case, the name of the file should be `kmoe.md`

2. The courses in your *Completed Courses* section are in the same line. The correct format of that section should be:

```
# Completed Courses

MMathPhil Mathematics and Philosophy (Oxford University)

**Cryptography**

Course|Files
:--|:--:
Cryptography I| [link]()
```

Where on `[link]()` you should link to some place that have files that you created in that course. If you do not have any public file/folder to show, just leave a `-` in that place.

Can you make another Pull Request to fix those points?

If you need some help, just let me know.

Thanks again for join us! :smile:

**Comment by ericdouglas** [comment]
@kmoe 

I updated the manner to enrolling in our course to be more scalable.

Can you create your profile **[here](https://github.com/open-source-society/computer-science-and-engineering/issues/28)** again?

Sorry for that, but in that way will be much more easy for all of us :smile:

**Comment by kmoe** [comment]
Sure @ericdouglas, I'll do that this lunchtime. Thanks for the quick response!

**Comment by ericdouglas** [comment]
@kmoe :wink:

**Comment by kmoe** [comment]
agh, sorry, opened a new PR before I saw that https://github.com/open-source-society/computer-science-and-engineering/pull/70

**Comment by ericdouglas** [comment]
@kmoe no problem! :wink:

**Pull request merged**
