### PR TITLE
hoi-bat-pham.md

### PR DESCRIPTION
**Pull request by HoiBatPham**

### CODE REVIEW

**Comment by ericdouglas** [comment]
Thanks for enrolling @HoiBatPham ! :smile:

**Comment by HoiBatPham** [comment]
Thank YOU for creating this project! :-)

**Comment by ericdouglas** [comment]
:wink:

**Comment by ericdouglas** [comment]
@HoiBatPham 

I updated the manner to enrolling in our course to be more scalable.

Can you create your profile **[here](https://github.com/open-source-society/computer-science-and-engineering/issues/28)** again?

Sorry for that, but in that way will be much more easy for all of us :smile:

**Pull request merged**
